baseURL = 'https://lamalab.org'
languageCode = 'en-us'
relativeURLs = true
title = 'Lab for AI in Materials Science'
theme = "cactus"
colortheme = "white"
description = "we are a research group trying to teach computers how to design materials that work in the real world"
enableEmoji = true
enableRobotsTXT = true
# Disable Google Analytics to avoid template errors
googleAnalytics = ""

[params]
mathjax = true
css = ["css/custom.css"]
logo = "png-file.png"
customHead = ["extra-head.html"]

[[params.social]]
name = "github"
link = "https://github.com/lamalab-org"
icon = "fab fa-github"

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/company/lamalab-org"
icon = "fab fa-linkedin"

[[params.social]]
name = "x"
link = "https://x.com/jablonkagroup"
icon = "fab fa-x-twitter"

[[params.social]]
name = "bluesky"
link = "https://bsky.app/profile/jablonkagroup.bsky.social"
icon = "fab fa-bluesky"

[[menu.main]]
name = "team"
url = "/team"
weight = 1

[[menu.main]]
name = "pubs"
url = "/publications"
weight = 2


[[menu.main]]
name = "benches, data, tools"
url = "/benches"
weight = 4

[[menu.main]]
name = "vibes"
url = "/gallery"
weight = 5

[[menu.main]]
name = "blog"
url = "https://lamalaborg.substack.com"
weight = 6


[[menu.main]]
name = "teaching"
url = "/teaching"
weight = 6

[[menu.main]]
name = "mentoring"
url = "/mentoring"
weight = 6


[[menu.main]]
name = "handbook"
url = "https://lamalab-org.github.io/group-handbook/"
weight = 6